# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    flow_root_dir: '%kernel.project_dir%/../..'
    examples_path: '%flow_root_dir%/examples'
    dsl_definitions_path: '%flow_root_dir%/web/landing/resources/dsl.json'
    documentation_base_path: '%flow_root_dir%/documentation'
    scheme: '%env(SCHEME)%'
    domain: '%env(DOMAIN)%'
    router.request_context.base_url: '%env(SCHEME)%://%env(BASE_URL)%'
    router.request_context.host: '%env(DOMAIN)%'
    router.request_context.scheme: '%env(SCHEME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Flow\Website\:
        resource: '../src/Flow/Website/'
        exclude:
            - '../src/Flow/Website/Kernel.php'

    Flow\Website\Service\:
        resource: '../src/Flow/Website/Service/'

    Flow\Website\Factory\Github\ContributorsRequestFactory:
        arguments:
            $githubToken: '%env(GITHUB_TOKEN)%'

    Flow\Website\StaticSourceProvider\:
        resource: '../src/Flow/Website/StaticSourceProvider/'
        tags: ['static_content_generator.source_provider']

    Flow\Website\Service\Examples:
        arguments:
            $examplesPath: '%examples_path%'

    Flow\Website\Service\Documentation\DSLDefinitions:
        factory: ['Flow\Website\Service\Documentation\DSLDefinitions', 'fromJson']
        arguments:
            $definitionsPath: '%dsl_definitions_path%'

    Flow\Website\Service\Documentation\Pages:
        arguments:
            $basePath: '%documentation_base_path%'

    Flow\Website\Twig\:
        resource: '../src/Flow/Website/Twig/**/*Extension.php'
        tags: [twig.extension]

    Flow\Website\Twig\DSLExtension:
        arguments:
            $dslPath: '%dsl_definitions_path%'

    twig.markdown.league_common_mark_converter_factory:
        class: Flow\Website\Service\Markdown\LeagueCommonMarkConverterFactory