name: Documentation Linter

on:
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'examples/**'
      - 'README.md'
  push:
    branches:
      - "1.x"
    paths-ignore:
      - 'CHANGELOG.md'

# See https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation-linter:
    name: "Documentation Linter"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1, post_max_size=32M, upload_max_filesize=32M
          extensions: :psr, bcmath, dom, hash, json, mbstring, xml, xmlwriter, xmlreader, zlib, curl

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-8.2-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-8.2-locked-composer-

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Build Docs"
        run: "composer build:docs"

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Uncommitted changes detected, please run `composer build:docs` and commit the changes."
            git status
            exit 1
          else
            echo "No uncommitted changes."
          fi

      - name: "MD Link Linter"
        uses: "docker://norberttech/md-link-linter:latest"
        with:
          entrypoint: "/composer/vendor/bin/mdlinklint"
          args: "--exclude=vendor --exclude=tests --exclude=examples --exclude=documentation ."
