name: Static Analyze Tests

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/adapter/**'
      - 'src/bridge/**'
      - 'src/core/**'
      - 'src/cli/**'
      - 'tools/**'
      - 'composer.lock'
  push:
    branches: [ 1.x ]
    paths-ignore:
      - 'CHANGELOG.md'

# See https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  static-analyze:
    name: "Static Analyze"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.2"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          extensions: :psr, bcmath, dom, hash, json, mbstring, xml, xmlwriter, xmlreader, zlib

      - name: "Create cache directories"
        run: |
          mkdir -p var/phpstan-tests/cache

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-${{ matrix.php-version }}-locked-composer-tests-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-locked-composer-tests-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Cache phpstan results"
        uses: "actions/cache@v4"
        with:
          path: "var/phpstan-tests/cache"
          key: "php-${{ matrix.php-version }}-cache-phpstan-tests-${{ github.run_id }}"
          restore-keys: |
            php-${{ matrix.php-version }}-cache-phpstan-tests-

      - name: "Static Analyze Tests - PHPStan"
        run: "composer static:analyze:phpstan:tests --error-format=github"
